name: 'Setup Ghjk'
description: 'Installs ghjk and syncs ports'
inputs:
  version:
    description: 'Github version/branch to install from'
    required: false
  skip-deno-install:
    description: 'Use to avoid share another deno exec already installed in workflow'
    required: false
    default: false
  installer-url:
    description: 'Alternative installer script to use'
    required: false
  sync:
    description: 'Disable to skip syncing ports'
    required: true
    default: true
  cache-disable:
    description: 'Enable to skip caching the GHJK dir'
    required: true
    default: false
  cache-save-if:
    description: "Toggle cache saving. To disable cache restore as well, use cache-disable"
    required: true
    default: true
  cache-key-prefix:
    description: 'Prefix to use for the cache key. v0-ghjk by default'
    required: false
  cache-key-env-vars:
    description: "Additional environment variables to include in the cache key, separated by comma."
    required: false

runs:
  using: node20
  main: gh_action/main.js
  post: gh_action/post.js
  post-if: "success() || env.CACHE_ON_FAILURE == 'true'"
