name: 'Setup Ghjk'
description: 'Installs ghjk and syncs ports'
inputs:
  version:
    description: 'Github version/branch to install from'
    required: true
    default: 'v0.1.0-alpha'
  installer-uri:
    description: 'Alternative installer script to use'
    required: false
  sync:
    description: 'Disable to skip syncing ports'
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - id: install-ghjk
      shell: bash
      run: |
        deno run -A ${{ 
        inputs.installer-uri 
        || (inputs.version && format('https://raw.github.com/metatypedev/ghjk/{0}/install.ts', inputs.version)) 
        || format('{0}install.ts', github.action_path) }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - id: sync-ghjk
      shell: bash
      if: ${{ inputs.sync }}
      run: |
        ghjk config
        ghjk ports sync
    - id: ghjk-outputs
      shell: bash
      run: |
        echo "GHJK_DIR=$HOME/.local/share/ghjk" >> $GITHUB_OUTPUT
        echo "BASH_ENV=$HOME/.local/share/ghjk/env.sh" >> $GITHUB_ENV
