name: 'Setup Ghjk'
description: 'Installs ghjk and syncs ports'
inputs:
  version:
    description: 'Github version/branch to install from'
    required: false
  skip-deno-install:
    description: 'Use to avoid share another deno exec already installed in workflow'
    required: false
    default: false
  installer-url:
    description: 'Alternative installer script to use'
    required: false
  sync:
    description: 'Disable to skip syncing ports'
    required: true
    default: true

runs:
  using: node20
  main: gh_action/index.js
