name: 'Setup Ghjk'
description: 'Installs ghjk and optionally syncs according to the config'
inputs:
  version:
    description: 'Github version/branch to install from'
    required: true
    default: 'v0.1.0-alpha'
  installer-uri:
    description: 'Alternative installer script to use'
    required: false
  sync:
    description: 'Disable to skip syncing ports'
    required: true
    default: true
runs:
  using: "composite"
  steps:
    - id: install-ghjk
      shell: bash
      env:
        DEFAULT_INSTALL_URL: "${{ github.action_path }}/install.ts"
      run: |
        deno run -A ${${{ inputs.installer-uri }}:-$DEFAULT_INSTALL_URL}
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - id: sync-ghjk
      shell: bash
      if: ${{ inputs.sync }}
      run: |
        ghjk config
        ghjk ports sync
    - id: ghjk-outputs
      shell: bash
      run: |
        echo "GHJK_DIR=$HOME/.local/share/ghjk" >> $GITHUB_OUTPUT
        echo "BASH_ENV=$HOME/.local/share/ghjk/env.sh" >> $GITHUB_ENV
