#!/usr/bin/env bash

set -Eeuo pipefail

PACKAGE=@bytecodealliance/jco
PACKAGE_INTERNAL=jco
BIN="jco"
BIN_PATH="${ASDF_INSTALL_PATH}/src/jco.js"

if [[ "${ASDF_INSTALL_TYPE:-version}" == 'ref' ]]; then
    echo >&2 "⛔ This plugin does not support installing by ref."
    exit 1
fi

TARBALL_URL="https://registry.npmjs.org/${PACKAGE}/-/${PACKAGE_INTERNAL}-${ASDF_INSTALL_VERSION}.tgz"
echo "Downloading ${PACKAGE} v${ASDF_INSTALL_VERSION} from ${TARBALL_URL}"

mkdir -p "${ASDF_INSTALL_PATH}"
curl --silent --fail --show-error --location "${TARBALL_URL}" |
    tar xzf - --strip-components=1 --no-same-owner -C "${ASDF_INSTALL_PATH}"

chmod +x "${BIN_PATH}"
mkdir -p "${ASDF_INSTALL_PATH}/bin"
ln -sf "${BIN_PATH}" "${ASDF_INSTALL_PATH}/bin/${BIN}"
